#!/bin/bash

#sanify check

if [ $# -lt 1 ] ; then
	echo "usage $0 ROOTDIR"
	exit 1
fi

rootdir=$1

if [ -z "$rootdir" ]; then
	echo "ROOTDIR is not set."
	exit 1
fi

# Check root directory
if [ ! -d $rootdir ]; then
	echo "$rootdir: should be a directory."
	exit 1
fi

pushd $rootdir > /dev/null

[ -f etc/localtime ] && rm -f etc/localtime
ln -s ../usr/share/zoneinfo/Host etc/localtime
cp -fp /etc/localtime usr/share/zoneinfo/Host

# Clean /run
rm -rf run/* > /dev/null 2>&1

popd > /dev/null
